// <auto-generated />
using System;
using DataMais.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataMais.Migrations
{
    [DbContext(typeof(DataMaisDbContext))]
    [Migration("20260227202334_colunas")]
    partial class colunas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataMais.Models.Cilindro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CargaNominalA")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("CargaNominalB")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoCliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoInterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("ComprimentoHaste")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataFabricacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("DiametroHaste")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("DiametroInterno")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Fabricante")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("HistereseAlarmeA")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("HistereseAlarmeB")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("MaximaPressaoSegurancaA")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("MaximaPressaoSegurancaB")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("MaximaPressaoSuportadaA")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("MaximaPressaoSuportadaB")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("PercentualVariacaoAlarmeA")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PercentualVariacaoAlarmeB")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PercentualVariacaoDesligaProcessoA")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PercentualVariacaoDesligaProcessoB")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PreCargaA")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PreCargaB")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("TempoDuracaoCargaA")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("TempoDuracaoCargaB")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("TempoRampaDescidaA")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("TempoRampaDescidaB")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("TempoRampaSubidaA")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("TempoRampaSubidaB")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoInterno")
                        .IsUnique();

                    b.HasIndex("ClienteId", "CodigoCliente")
                        .IsUnique();

                    b.ToTable("Cilindros");
                });

            modelBuilder.Entity("DataMais.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cnpj")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.Property<string>("Contato")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.HasIndex("Email");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("DataMais.Models.Ensaio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CamaraTestada")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("CilindroId")
                        .HasColumnType("integer");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("PressaoCargaConfigurada")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("TempoCargaConfigurado")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CilindroId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Ensaios");
                });

            modelBuilder.Entity("DataMais.Models.ModbusConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("ByteOrder")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EnderecoRegistro")
                        .HasColumnType("integer");

                    b.Property<decimal?>("FatorConversao")
                        .HasColumnType("decimal(10,6)");

                    b.Property<string>("FuncaoModbus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("Offset")
                        .HasColumnType("decimal(10,6)");

                    b.Property<int>("OrdemLeitura")
                        .HasColumnType("integer");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeRegistros")
                        .HasColumnType("integer");

                    b.Property<byte>("SlaveId")
                        .HasColumnType("smallint");

                    b.Property<string>("TipoDado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Unidade")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.HasIndex("IpAddress", "OrdemLeitura");

                    b.HasIndex("Nome", "FuncaoModbus")
                        .IsUnique();

                    b.ToTable("ModbusConfigs");
                });

            modelBuilder.Entity("DataMais.Models.Relatorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CaminhoArquivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("CilindroId")
                        .HasColumnType("integer");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EnsaioId")
                        .HasColumnType("integer");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CilindroId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Data");

                    b.HasIndex("EnsaioId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Relatorios");
                });

            modelBuilder.Entity("DataMais.Models.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("InputMax")
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal?>("InputMin")
                        .HasColumnType("decimal(10,6)");

                    b.Property<int?>("ModbusConfigId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("OutputMax")
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal?>("OutputMin")
                        .HasColumnType("decimal(10,6)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Unidade")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ModbusConfigId");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Sensores");
                });

            modelBuilder.Entity("DataMais.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("DataMais.Models.Cilindro", b =>
                {
                    b.HasOne("DataMais.Models.Cliente", "Cliente")
                        .WithMany("Cilindros")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("DataMais.Models.Ensaio", b =>
                {
                    b.HasOne("DataMais.Models.Cilindro", "Cilindro")
                        .WithMany("Ensaios")
                        .HasForeignKey("CilindroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataMais.Models.Cliente", "Cliente")
                        .WithMany("Ensaios")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cilindro");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("DataMais.Models.Relatorio", b =>
                {
                    b.HasOne("DataMais.Models.Cilindro", "Cilindro")
                        .WithMany("Relatorios")
                        .HasForeignKey("CilindroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataMais.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataMais.Models.Ensaio", "Ensaio")
                        .WithMany("Relatorios")
                        .HasForeignKey("EnsaioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cilindro");

                    b.Navigation("Cliente");

                    b.Navigation("Ensaio");
                });

            modelBuilder.Entity("DataMais.Models.Sensor", b =>
                {
                    b.HasOne("DataMais.Models.ModbusConfig", "ModbusConfig")
                        .WithMany()
                        .HasForeignKey("ModbusConfigId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ModbusConfig");
                });

            modelBuilder.Entity("DataMais.Models.Cilindro", b =>
                {
                    b.Navigation("Ensaios");

                    b.Navigation("Relatorios");
                });

            modelBuilder.Entity("DataMais.Models.Cliente", b =>
                {
                    b.Navigation("Cilindros");

                    b.Navigation("Ensaios");
                });

            modelBuilder.Entity("DataMais.Models.Ensaio", b =>
                {
                    b.Navigation("Relatorios");
                });
#pragma warning restore 612, 618
        }
    }
}
