// <auto-generated />
using System;
using DataMais.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataMais.Migrations
{
    [DbContext(typeof(DataMaisDbContext))]
    [Migration("20260803202157_CorrigeFkRespostasCampoRelatorio")]
    partial class CorrigeFkRespostasCampoRelatorio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataMais.Models.CampoRelatorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<bool>("ReprovaSeSim")
                        .HasColumnType("boolean");

                    b.Property<string>("Secao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TipoResposta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("DataExclusao");

                    b.HasIndex("Ordem");

                    b.ToTable("CamposRelatorio");
                });

            modelBuilder.Entity("DataMais.Models.Cilindro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CargaNominalA")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("CargaNominalB")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoCliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoInterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("ComprimentoHaste")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataFabricacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("DiametroHaste")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("DiametroInterno")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Fabricante")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FluidoUtilizado")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("HistereseAlarmeA")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("HistereseAlarmeB")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("LimitePassagemCamaraA")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("LimitePassagemCamaraB")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MaximaPressaoA")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MaximaPressaoB")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PartNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("PercentualVariacaoAlarmeA")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PercentualVariacaoAlarmeB")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PercentualVariacaoDesligaProcessoA")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PercentualVariacaoDesligaProcessoB")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PreCargaA")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PreCargaB")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("TempoDuracaoCargaA")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("TempoDuracaoCargaB")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("TempoRampaDescidaA")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("TempoRampaDescidaB")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("TempoRampaSubidaA")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("TempoRampaSubidaB")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoInterno")
                        .IsUnique();

                    b.HasIndex("ClienteId", "CodigoCliente")
                        .IsUnique();

                    b.ToTable("Cilindros");
                });

            modelBuilder.Entity("DataMais.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cnpj")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.Property<string>("Contato")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.HasIndex("Email");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("DataMais.Models.ContadorRelatorio", b =>
                {
                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<int>("UltimoNumero")
                        .HasColumnType("integer");

                    b.HasKey("Ano");

                    b.ToTable("ContadoresRelatorio");
                });

            modelBuilder.Entity("DataMais.Models.Ensaio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CamaraTestada")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("CilindroId")
                        .HasColumnType("integer");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LocalTeste")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("OrdemServico")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("PressaoCargaConfigurada")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("TempoCargaConfigurado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Vessel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CilindroId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Ensaios");
                });

            modelBuilder.Entity("DataMais.Models.EnsaioEtapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Camara")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataFimContagem")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataInicioContagem")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EnsaioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PressaoCargaConfigurada")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TempoCargaConfigurado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Tentativa")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("EnsaioId", "Camara", "Tentativa")
                        .IsUnique();

                    b.ToTable("EnsaioEtapas");
                });

            modelBuilder.Entity("DataMais.Models.ModbusConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("ByteOrder")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EnderecoRegistro")
                        .HasColumnType("integer");

                    b.Property<decimal?>("FatorConversao")
                        .HasColumnType("decimal(10,6)");

                    b.Property<string>("FuncaoModbus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("Offset")
                        .HasColumnType("decimal(10,6)");

                    b.Property<int>("OrdemLeitura")
                        .HasColumnType("integer");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeRegistros")
                        .HasColumnType("integer");

                    b.Property<byte>("SlaveId")
                        .HasColumnType("smallint");

                    b.Property<string>("TipoDado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Unidade")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.HasIndex("IpAddress", "OrdemLeitura");

                    b.HasIndex("Nome", "FuncaoModbus")
                        .IsUnique();

                    b.ToTable("ModbusConfigs");
                });

            modelBuilder.Entity("DataMais.Models.Relatorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CaminhoArquivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("CilindroId")
                        .HasColumnType("integer");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("ConcluidoPorNome")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ConcluidoPorUsuarioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EnsaioId")
                        .HasColumnType("integer");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Rascunho");

                    b.Property<int>("Versao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CilindroId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Data");

                    b.HasIndex("EnsaioId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Relatorios");
                });

            modelBuilder.Entity("DataMais.Models.RelatorioVersao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumeroVersao")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("RelatorioId")
                        .HasColumnType("integer");

                    b.Property<string>("RespostasJson")
                        .HasColumnType("text");

                    b.Property<string>("Resultado")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioNome")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("RelatorioId");

                    b.ToTable("RelatorioVersoes");
                });

            modelBuilder.Entity("DataMais.Models.RespostaCampoRelatorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CampoRelatorioId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RelatorioId")
                        .HasColumnType("integer");

                    b.Property<string>("Valor")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CampoRelatorioId");

                    b.HasIndex("RelatorioId");

                    b.HasIndex("RelatorioId", "CampoRelatorioId")
                        .IsUnique();

                    b.ToTable("RespostasCampoRelatorio");
                });

            modelBuilder.Entity("DataMais.Models.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("InputMax")
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal?>("InputMin")
                        .HasColumnType("decimal(10,6)");

                    b.Property<int?>("ModbusConfigId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("OutputMax")
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal?>("OutputMin")
                        .HasColumnType("decimal(10,6)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Unidade")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ModbusConfigId");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Sensores");
                });

            modelBuilder.Entity("DataMais.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("DataMais.Models.Cilindro", b =>
                {
                    b.HasOne("DataMais.Models.Cliente", "Cliente")
                        .WithMany("Cilindros")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("DataMais.Models.Ensaio", b =>
                {
                    b.HasOne("DataMais.Models.Cilindro", "Cilindro")
                        .WithMany("Ensaios")
                        .HasForeignKey("CilindroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataMais.Models.Cliente", "Cliente")
                        .WithMany("Ensaios")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cilindro");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("DataMais.Models.EnsaioEtapa", b =>
                {
                    b.HasOne("DataMais.Models.Ensaio", "Ensaio")
                        .WithMany("Etapas")
                        .HasForeignKey("EnsaioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ensaio");
                });

            modelBuilder.Entity("DataMais.Models.Relatorio", b =>
                {
                    b.HasOne("DataMais.Models.Cilindro", "Cilindro")
                        .WithMany("Relatorios")
                        .HasForeignKey("CilindroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataMais.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataMais.Models.Ensaio", "Ensaio")
                        .WithMany("Relatorios")
                        .HasForeignKey("EnsaioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cilindro");

                    b.Navigation("Cliente");

                    b.Navigation("Ensaio");
                });

            modelBuilder.Entity("DataMais.Models.RelatorioVersao", b =>
                {
                    b.HasOne("DataMais.Models.Relatorio", "Relatorio")
                        .WithMany("Versoes")
                        .HasForeignKey("RelatorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Relatorio");
                });

            modelBuilder.Entity("DataMais.Models.RespostaCampoRelatorio", b =>
                {
                    b.HasOne("DataMais.Models.CampoRelatorio", "CampoRelatorio")
                        .WithMany("Respostas")
                        .HasForeignKey("CampoRelatorioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataMais.Models.Relatorio", "Relatorio")
                        .WithMany("RespostasCampos")
                        .HasForeignKey("RelatorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CampoRelatorio");

                    b.Navigation("Relatorio");
                });

            modelBuilder.Entity("DataMais.Models.Sensor", b =>
                {
                    b.HasOne("DataMais.Models.ModbusConfig", "ModbusConfig")
                        .WithMany()
                        .HasForeignKey("ModbusConfigId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ModbusConfig");
                });

            modelBuilder.Entity("DataMais.Models.CampoRelatorio", b =>
                {
                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("DataMais.Models.Cilindro", b =>
                {
                    b.Navigation("Ensaios");

                    b.Navigation("Relatorios");
                });

            modelBuilder.Entity("DataMais.Models.Cliente", b =>
                {
                    b.Navigation("Cilindros");

                    b.Navigation("Ensaios");
                });

            modelBuilder.Entity("DataMais.Models.Ensaio", b =>
                {
                    b.Navigation("Etapas");

                    b.Navigation("Relatorios");
                });

            modelBuilder.Entity("DataMais.Models.Relatorio", b =>
                {
                    b.Navigation("RespostasCampos");

                    b.Navigation("Versoes");
                });
#pragma warning restore 612, 618
        }
    }
}
