CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226170530_InitialCreate') THEN
    CREATE TABLE "Clientes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nome" character varying(200) NOT NULL,
        "Cnpj" character varying(18),
        "Contato" character varying(100),
        "Email" character varying(100),
        "DataCriacao" timestamp with time zone NOT NULL,
        "DataAtualizacao" timestamp with time zone,
        CONSTRAINT "PK_Clientes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226170530_InitialCreate') THEN
    CREATE TABLE "ModbusConfigs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nome" character varying(100) NOT NULL,
        "Descricao" character varying(500),
        "IpAddress" character varying(50) NOT NULL,
        "Port" integer NOT NULL,
        "SlaveId" smallint NOT NULL,
        "FuncaoModbus" character varying(20) NOT NULL,
        "EnderecoRegistro" integer NOT NULL,
        "QuantidadeRegistros" integer NOT NULL,
        "TipoDado" character varying(20) NOT NULL,
        "ByteOrder" character varying(10) NOT NULL,
        "FatorConversao" numeric(10,6),
        "Offset" numeric(10,6),
        "Unidade" character varying(20),
        "OrdemLeitura" integer NOT NULL,
        "Ativo" boolean NOT NULL,
        "DataCriacao" timestamp with time zone NOT NULL,
        "DataAtualizacao" timestamp with time zone,
        CONSTRAINT "PK_ModbusConfigs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226170530_InitialCreate') THEN
    CREATE TABLE "Usuarios" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nome" character varying(100) NOT NULL,
        "Email" character varying(100) NOT NULL,
        "SenhaHash" character varying(200) NOT NULL,
        "Role" character varying(50),
        "Ativo" boolean NOT NULL,
        "DataCriacao" timestamp with time zone NOT NULL,
        "DataAtualizacao" timestamp with time zone,
        "UltimoLogin" timestamp with time zone,
        CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226170530_InitialCreate') THEN
    CREATE TABLE "Cilindros" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nome" character varying(200) NOT NULL,
        "Descricao" character varying(1000),
        "CodigoCliente" character varying(50) NOT NULL,
        "CodigoInterno" character varying(50) NOT NULL,
        "Modelo" character varying(100),
        "Fabricante" character varying(100),
        "DataFabricacao" timestamp with time zone,
        "DiametroInterno" numeric(10,2),
        "ComprimentoHaste" numeric(10,2),
        "DiametroHaste" numeric(10,2),
        "MaximaPressaoSuportadaA" numeric(10,2),
        "MaximaPressaoSuportadaB" numeric(10,2),
        "MaximaPressaoSegurancaA" numeric(10,2),
        "MaximaPressaoSegurancaB" numeric(10,2),
        "PreCargaA" numeric(10,2),
        "CargaNominalA" numeric(10,2),
        "TempoRampaSubidaA" numeric(10,2),
        "TempoDuracaoCargaA" numeric(10,2),
        "TempoRampaDescidaA" numeric(10,2),
        "PercentualVariacaoAlarmeA" numeric(10,2),
        "HistereseAlarmeA" numeric(10,2),
        "PercentualVariacaoDesligaProcessoA" numeric(10,2),
        "PreCargaB" numeric(10,2),
        "CargaNominalB" numeric(10,2),
        "TempoRampaSubidaB" numeric(10,2),
        "TempoDuracaoCargaB" numeric(10,2),
        "TempoRampaDescidaB" numeric(10,2),
        "PercentualVariacaoAlarmeB" numeric(10,2),
        "HistereseAlarmeB" numeric(10,2),
        "PercentualVariacaoDesligaProcessoB" numeric(10,2),
        "ClienteId" integer NOT NULL,
        "DataCriacao" timestamp with time zone NOT NULL,
        "DataAtualizacao" timestamp with time zone,
        CONSTRAINT "PK_Cilindros" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Cilindros_Clientes_ClienteId" FOREIGN KEY ("ClienteId") REFERENCES "Clientes" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226170530_InitialCreate') THEN
    CREATE TABLE "Sensores" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nome" character varying(100) NOT NULL,
        "Descricao" character varying(500),
        "Tipo" character varying(50) NOT NULL,
        "Unidade" character varying(20),
        "ModbusConfigId" integer,
        "Ativo" boolean NOT NULL,
        "DataCriacao" timestamp with time zone NOT NULL,
        "DataAtualizacao" timestamp with time zone,
        CONSTRAINT "PK_Sensores" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Sensores_ModbusConfigs_ModbusConfigId" FOREIGN KEY ("ModbusConfigId") REFERENCES "ModbusConfigs" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226170530_InitialCreate') THEN
    CREATE TABLE "Ensaios" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Numero" character varying(100) NOT NULL,
        "Status" character varying(50) NOT NULL,
        "DataInicio" timestamp with time zone,
        "DataFim" timestamp with time zone,
        "Observacoes" character varying(1000),
        "ClienteId" integer NOT NULL,
        "CilindroId" integer NOT NULL,
        "DataCriacao" timestamp with time zone NOT NULL,
        "DataAtualizacao" timestamp with time zone,
        CONSTRAINT "PK_Ensaios" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Ensaios_Cilindros_CilindroId" FOREIGN KEY ("CilindroId") REFERENCES "Cilindros" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Ensaios_Clientes_ClienteId" FOREIGN KEY ("ClienteId") REFERENCES "Clientes" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226170530_InitialCreate') THEN
    CREATE TABLE "Relatorios" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Numero" character varying(100) NOT NULL,
        "Data" timestamp with time zone NOT NULL,
        "Observacoes" character varying(1000),
        "CaminhoArquivo" character varying(500),
        "ClienteId" integer NOT NULL,
        "CilindroId" integer NOT NULL,
        "EnsaioId" integer,
        "DataCriacao" timestamp with time zone NOT NULL,
        "DataAtualizacao" timestamp with time zone,
        CONSTRAINT "PK_Relatorios" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Relatorios_Cilindros_CilindroId" FOREIGN KEY ("CilindroId") REFERENCES "Cilindros" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Relatorios_Clientes_ClienteId" FOREIGN KEY ("ClienteId") REFERENCES "Clientes" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Relatorios_Ensaios_EnsaioId" FOREIGN KEY ("EnsaioId") REFERENCES "Ensaios" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226170530_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Cilindros_ClienteId_CodigoCliente" ON "Cilindros" ("ClienteId", "CodigoCliente");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226170530_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Cilindros_CodigoInterno" ON "Cilindros" ("CodigoInterno");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226170530_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Clientes_Cnpj" ON "Clientes" ("Cnpj");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226170530_InitialCreate') THEN
    CREATE INDEX "IX_Clientes_Email" ON "Clientes" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226170530_InitialCreate') THEN
    CREATE INDEX "IX_Ensaios_CilindroId" ON "Ensaios" ("CilindroId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226170530_InitialCreate') THEN
    CREATE INDEX "IX_Ensaios_ClienteId" ON "Ensaios" ("ClienteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226170530_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Ensaios_Numero" ON "Ensaios" ("Numero");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226170530_InitialCreate') THEN
    CREATE INDEX "IX_Ensaios_Status" ON "Ensaios" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226170530_InitialCreate') THEN
    CREATE INDEX "IX_ModbusConfigs_IpAddress_OrdemLeitura" ON "ModbusConfigs" ("IpAddress", "OrdemLeitura");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226170530_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_ModbusConfigs_Nome" ON "ModbusConfigs" ("Nome");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226170530_InitialCreate') THEN
    CREATE INDEX "IX_Relatorios_CilindroId" ON "Relatorios" ("CilindroId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226170530_InitialCreate') THEN
    CREATE INDEX "IX_Relatorios_ClienteId" ON "Relatorios" ("ClienteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226170530_InitialCreate') THEN
    CREATE INDEX "IX_Relatorios_Data" ON "Relatorios" ("Data");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226170530_InitialCreate') THEN
    CREATE INDEX "IX_Relatorios_EnsaioId" ON "Relatorios" ("EnsaioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226170530_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Relatorios_Numero" ON "Relatorios" ("Numero");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226170530_InitialCreate') THEN
    CREATE INDEX "IX_Sensores_ModbusConfigId" ON "Sensores" ("ModbusConfigId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226170530_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Sensores_Nome" ON "Sensores" ("Nome");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226170530_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Usuarios_Email" ON "Usuarios" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226170530_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260226170530_InitialCreate', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226225232_AddScaleToSensor') THEN
    ALTER TABLE "Sensores" ADD "Scale" numeric(10,6);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226225232_AddScaleToSensor') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260226225232_AddScaleToSensor', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227125657_UpdateSensorCalibrationFields') THEN
    ALTER TABLE "Sensores" ADD "InputMin" numeric(10,6);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227125657_UpdateSensorCalibrationFields') THEN
    ALTER TABLE "Sensores" ADD "OutputMin" numeric(10,6);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227125657_UpdateSensorCalibrationFields') THEN
    ALTER TABLE "Sensores" ADD "InputMax" numeric(10,6);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227125657_UpdateSensorCalibrationFields') THEN
    ALTER TABLE "Sensores" ADD "OutputMax" numeric(10,6);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227125657_UpdateSensorCalibrationFields') THEN
    ALTER TABLE "Sensores" DROP COLUMN "Scale";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227125657_UpdateSensorCalibrationFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260227125657_UpdateSensorCalibrationFields', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227170929_RemoveUniqueIndexNomeModbusConfig') THEN
    DROP INDEX "IX_ModbusConfigs_Nome";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227170929_RemoveUniqueIndexNomeModbusConfig') THEN
    CREATE INDEX "IX_ModbusConfigs_Nome" ON "ModbusConfigs" ("Nome");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227170929_RemoveUniqueIndexNomeModbusConfig') THEN
    CREATE INDEX "IX_ModbusConfigs_Nome_FuncaoModbus" ON "ModbusConfigs" ("Nome", "FuncaoModbus");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227170929_RemoveUniqueIndexNomeModbusConfig') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260227170929_RemoveUniqueIndexNomeModbusConfig', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227171429_AddUniqueIndexNomeFuncaoModbus') THEN
    DROP INDEX "IX_ModbusConfigs_Nome_FuncaoModbus";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227171429_AddUniqueIndexNomeFuncaoModbus') THEN
    CREATE UNIQUE INDEX "IX_ModbusConfigs_Nome_FuncaoModbus" ON "ModbusConfigs" ("Nome", "FuncaoModbus");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227171429_AddUniqueIndexNomeFuncaoModbus') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260227171429_AddUniqueIndexNomeFuncaoModbus', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227202334_colunas') THEN
    ALTER TABLE "Ensaios" ADD "CamaraTestada" character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227202334_colunas') THEN
    ALTER TABLE "Ensaios" ADD "PressaoCargaConfigurada" numeric(10,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227202334_colunas') THEN
    ALTER TABLE "Ensaios" ADD "TempoCargaConfigurado" numeric(10,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227202334_colunas') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260227202334_colunas', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260228133440_UpdateCilindroPressaoMaxima') THEN
    ALTER TABLE "Cilindros" ADD "MaximaPressaoA" numeric(10,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260228133440_UpdateCilindroPressaoMaxima') THEN
    ALTER TABLE "Cilindros" ADD "MaximaPressaoB" numeric(10,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260228133440_UpdateCilindroPressaoMaxima') THEN

                    UPDATE "Cilindros"
                    SET "MaximaPressaoA" = COALESCE("MaximaPressaoSuportadaA", 350),
                        "MaximaPressaoB" = COALESCE("MaximaPressaoSuportadaB", 350)
                    WHERE "MaximaPressaoA" IS NULL OR "MaximaPressaoB" IS NULL;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260228133440_UpdateCilindroPressaoMaxima') THEN
    ALTER TABLE "Cilindros" ALTER COLUMN "MaximaPressaoA" SET DEFAULT 350.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260228133440_UpdateCilindroPressaoMaxima') THEN
    ALTER TABLE "Cilindros" ALTER COLUMN "MaximaPressaoB" SET DEFAULT 350.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260228133440_UpdateCilindroPressaoMaxima') THEN
    ALTER TABLE "Cilindros" DROP COLUMN "MaximaPressaoSegurancaA";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260228133440_UpdateCilindroPressaoMaxima') THEN
    ALTER TABLE "Cilindros" DROP COLUMN "MaximaPressaoSegurancaB";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260228133440_UpdateCilindroPressaoMaxima') THEN
    ALTER TABLE "Cilindros" DROP COLUMN "MaximaPressaoSuportadaA";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260228133440_UpdateCilindroPressaoMaxima') THEN
    ALTER TABLE "Cilindros" DROP COLUMN "MaximaPressaoSuportadaB";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260228133440_UpdateCilindroPressaoMaxima') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260228133440_UpdateCilindroPressaoMaxima', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260228193244_perguntas') THEN
    CREATE TABLE "CamposRelatorio" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nome" character varying(500) NOT NULL,
        "TipoResposta" character varying(50) NOT NULL,
        "Ordem" integer NOT NULL,
        "DataCriacao" timestamp with time zone NOT NULL,
        "DataExclusao" timestamp with time zone,
        CONSTRAINT "PK_CamposRelatorio" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260228193244_perguntas') THEN
    CREATE TABLE "RespostasCampoRelatorio" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RelatorioId" integer NOT NULL,
        "CampoRelatorioId" integer NOT NULL,
        "Valor" character varying(2000),
        "DataCriacao" timestamp with time zone NOT NULL,
        "DataAtualizacao" timestamp with time zone,
        "RelatorioId1" integer,
        CONSTRAINT "PK_RespostasCampoRelatorio" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RespostasCampoRelatorio_CamposRelatorio_CampoRelatorioId" FOREIGN KEY ("CampoRelatorioId") REFERENCES "CamposRelatorio" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_RespostasCampoRelatorio_Relatorios_RelatorioId" FOREIGN KEY ("RelatorioId") REFERENCES "Relatorios" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_RespostasCampoRelatorio_Relatorios_RelatorioId1" FOREIGN KEY ("RelatorioId1") REFERENCES "Relatorios" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260228193244_perguntas') THEN
    CREATE INDEX "IX_CamposRelatorio_DataExclusao" ON "CamposRelatorio" ("DataExclusao");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260228193244_perguntas') THEN
    CREATE INDEX "IX_CamposRelatorio_Ordem" ON "CamposRelatorio" ("Ordem");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260228193244_perguntas') THEN
    CREATE INDEX "IX_RespostasCampoRelatorio_CampoRelatorioId" ON "RespostasCampoRelatorio" ("CampoRelatorioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260228193244_perguntas') THEN
    CREATE INDEX "IX_RespostasCampoRelatorio_RelatorioId" ON "RespostasCampoRelatorio" ("RelatorioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260228193244_perguntas') THEN
    CREATE UNIQUE INDEX "IX_RespostasCampoRelatorio_RelatorioId_CampoRelatorioId" ON "RespostasCampoRelatorio" ("RelatorioId", "CampoRelatorioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260228193244_perguntas') THEN
    CREATE INDEX "IX_RespostasCampoRelatorio_RelatorioId1" ON "RespostasCampoRelatorio" ("RelatorioId1");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260228193244_perguntas') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260228193244_perguntas', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624014850_AddLimitePassagemCamara') THEN
    ALTER TABLE "Cilindros" ADD "LimitePassagemCamaraA" numeric(10,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624014850_AddLimitePassagemCamara') THEN
    ALTER TABLE "Cilindros" ADD "LimitePassagemCamaraB" numeric(10,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624014850_AddLimitePassagemCamara') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260624014850_AddLimitePassagemCamara', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260724144332_AddCamposCadastraisRev02') THEN
    ALTER TABLE "Ensaios" ADD "Departamento" character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260724144332_AddCamposCadastraisRev02') THEN
    ALTER TABLE "Ensaios" ADD "LocalTeste" character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260724144332_AddCamposCadastraisRev02') THEN
    ALTER TABLE "Ensaios" ADD "OrdemServico" character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260724144332_AddCamposCadastraisRev02') THEN
    ALTER TABLE "Ensaios" ADD "Vessel" character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260724144332_AddCamposCadastraisRev02') THEN
    ALTER TABLE "Cilindros" ADD "FluidoUtilizado" character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260724144332_AddCamposCadastraisRev02') THEN
    ALTER TABLE "Cilindros" ADD "NumeroSerie" character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260724144332_AddCamposCadastraisRev02') THEN
    ALTER TABLE "Cilindros" ADD "PartNumber" character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260724144332_AddCamposCadastraisRev02') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260724144332_AddCamposCadastraisRev02', '8.0.0');
    END IF;
END $EF$;
COMMIT;

